import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.hero_section}>
      <Navbar/>
      <div className={styles.hero_content}>
        <h4>Top Construction Company in India</h4>
        <h1>L&T Engineering & Construction Division</h1>
        <div className={styles.hero_content_data}>
          <p>
            L&T Construction, India's largest construction organization and
            ranked among the world's top 30 contractors.
          </p>
        </div>
      </div>
    </div>
    </>
  )
}
